#!/usr/bin/env sh
set -e

# Protect master from accidental commits.
branchName=$(git branch | grep '*' | sed 's/* //')
mainBranchName='main'
developBranchName='develop'

if [ $branchName == $mainBranchName ]
then
  echo -e "\n🚫 Commit directly to $mainBranchName branch is not allowed!\n" && exit 1
fi

if [ $branchName == $developBranchName ]
then
  echo -e "\n🚫 Cannot push to remote $developBranchName branch, please create your own branch and use PR.\n"
  exit 1
fi

if [[ $branchName = *[![:ascii:]]* ]]
then
  echo -e "\n🚫 Branch name should not have any ascii and upper case letters, please rename your branch name.\n" && exit 1
fi

if [[ $branchName =~ [A-Z] ]]
then
  echo -e "\n🚫 Branch name should not have any ascii and upper case letters, please rename your branch name.\n" && exit 1
fi

echo -e ">> Finish checking branch name.\n==="

exit 0
