name: Publish Game

on:
    workflow_dispatch:

permissions: {}

jobs:
    build:
        name: Build game
        outputs:
            artifact-id: ${{ steps.upload.outputs.artifact-id }}
        runs-on: ubuntu-latest
        env:
            VERSION: 4.6.3
            SAVE_DIR: bin
        permissions:
          id-token: write
          contents: read
          attestations: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              with:
                persist-credentials: false
            
            - name: Cache Godot engine + export templates
              id: cache
              uses: actions/cache@v5
              with:
                path: ${{ env.SAVE_DIR }}/
                key: godot-v${{ env.VERSION }}-linux64
            
            - name: Download Godot
              if: steps.cache.outputs.cache-hit == ''
              run: |
                curl -o ${{ env.SAVE_DIR }}/godot https://downloads.godotengine.org/?version=${{ env.VERSION }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64
                curl -o ${{ env.SAVE_DIR }}/export-templates.tpz https://downloads.godotengine.org/?version=${{ env.VERSION }}&flavor=stable&slug=export_templates.tpz&platform=templates
            
            - name: Make Godot executable & alias Godot
              run: |
                mkdir ./bin
                chmod +x ./bin/godot
                alias godot="./bin/godot --headless"
            
            - parallel:
                - run: godot --export-release "Windows Desktop" ./project.godot
                - run: godot --export-release "macOS" ./project.godot
                - run: |
                    godot --export-release "Linux" ./project.godot
                    chmod +x ./build/neurojrpg
            
            - parallel:
              - uses: actions/attest@v4
                with:
                  subject-path: ./build/neurojrpg.exe
              
              - uses: actions/attest@v4
                with:
                  subject-path: ./build/neurojrpg.app
              
              - uses: actions/attest@v4
                with:
                  subject-path: ./build/neurojrpg
            
            - parallel:
                - run: cd build && zip ../dist/neuro-gef-win.zip ./neurojrpg.exe
                - run: cd build && zip -r ../dist/neuro-gef-mac.zip ./neurojrpg.app
                - run: cd build && tar -czvf ../dist/neuro-gef-linux.tar.gz ./neurojrpg
            
            - name: Upload artifacts
              id: upload
              uses: actions/upload-artifact@v7
              with:
                path: dist/*
                name: neuro-sama_gef
    
    distribute:
        name: Upload to itch.io
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: itch.io
            url: https://itch.io/
        steps:
            - name: Download artifacts
              id: download
              uses: actions/download-artifact@v8
              with:
                artifact-ids: ${{ needs.build.outputs.artifact-id }}
                path: ./dist
            
            - name: Setup itch.io credentials
              env:
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
              run: |
                curl -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
                echo "Butler ZIP SHA-256: $(sha256sum butler.zip)"
                unzip butler.zip
                butler login
            
            - name: Upload game binaries
              run: |
                butler push ${{ steps.download.outputs.download-path }}/neuro-gef-win.zip TeamFiltered/neuro-sama-the-good-the:windows-latest

            # - name: Post to Discord webhook
            #   run: |
            #     curl -X POST ${{ secrets.PUBLISH_WEBHOOK }}
